# Generated by Django 4.1 on 2022-08-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSystem', '0002_alter_students_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.CharField(max_length=200),
        ),
    ]
